"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 750

# Replace the "â¯" symbol in the prompt with "âœ"
[character] # The name of the module we are configuring is "character"
success_symbol = "[ğŸ¦‹](bold_green)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[ğŸ›](bold_red)"

[gcloud]
disabled = true

[git_branch]
symbol = "ğŸŒ±"

[nodejs]
symbol = "â˜•"