"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 750

[character]
success_symbol = "[ğŸ¦‹](bold_green)"
error_symbol = "[ğŸ›](bold_red)"

[gcloud]
disabled = true

[git_branch]
symbol = "ğŸŒ±"

[nodejs]
symbol = "â˜•"
